In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('../data/raw/investigations.csv')

In [4]:
df.head(3)

,NHTSA ACTION NUMBER,MAKE,MODEL,YEAR,COMPNAME,MFR_NAME,ODATE,CDATE,CAMPNO,SUBJECT,SUMMARY
0,AQ08001,PACE AMERICAN,TRAILER,2003.0,WHEELS,"PACE AMERICAN, INC.",20080618.0,20081029.0,NaN,PACE AMERICAN 573 RETRACTION,"BY LETTER DATED NOVEMBER 8, 2007, PACE AMERICA..."
1,AQ08001,PACE AMERICAN,TRAILER,2004.0,WHEELS,"PACE AMERICAN, INC.",20080618.0,20081029.0,NaN,PACE AMERICAN 573 RETRACTION,"BY LETTER DATED NOVEMBER 8, 2007, PACE AMERICA..."
2,AQ08001,PACE AMERICAN,TRAILER,2005.0,WHEELS,"PACE AMERICAN, INC.",20080618.0,20081029.0,NaN,PACE AMERICAN 573 RETRACTION,"BY LETTER DATED NOVEMBER 8, 2007, PACE AMERICA..."

In [5]:
df.shape

(154380, 11)

In [6]:
df.columns.to_list()

['NHTSA ACTION NUMBER',
 'MAKE',
 'MODEL',
 'YEAR',
 'COMPNAME',
 'MFR_NAME',
 'ODATE',
 'CDATE',
 'CAMPNO',
 'SUBJECT',
 'SUMMARY']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 154380 entries, 0 to 154379
Data columns (total 11 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   NHTSA ACTION NUMBER  154380 non-null  str
 1   MAKE                 153022 non-null  str
 2   MODEL                153022 non-null  str
 3   YEAR                 153022 non-null  float64
 4   COMPNAME             153020 non-null  str
 5   MFR_NAME             153022 non-null  str
 6   ODATE                154223 non-null  float64
 7   CDATE                78747 non-null   float64
 8   CAMPNO               125682 non-null  str
 9   SUBJECT              154380 non-null  str
 10  SUMMARY              153824 non-null  str
dtypes: float64(3), str(8)
memory usage: 13.0 MB

In [8]:
df.isna().sum()

NHTSA ACTION NUMBER        0
MAKE                    1358
MODEL                   1358
YEAR                    1358
COMPNAME                1360
MFR_NAME                1358
ODATE                    157
CDATE                  75633
CAMPNO                 28698
SUBJECT                    0
SUMMARY                  556
dtype: int64

In [9]:
df.nunique()

NHTSA ACTION NUMBER    5348
MAKE                    669
MODEL                  3705
YEAR                     63
COMPNAME                423
MFR_NAME                593
ODATE                  3505
CDATE                  3333
CAMPNO                 2819
SUBJECT                3784
SUMMARY                2706
dtype: int64

In [10]:
df.nunique()

NHTSA ACTION NUMBER    5348
MAKE                    669
MODEL                  3705
YEAR                     63
COMPNAME                423
MFR_NAME                593
ODATE                  3505
CDATE                  3333
CAMPNO                 2819
SUBJECT                3784
SUMMARY                2706
dtype: int64

In [13]:
df["NHTSA ACTION NUMBER"].nunique()

5348

In [14]:
df.loc[df["CAMPNO"].notna(), [
    "NHTSA ACTION NUMBER",
    "CAMPNO",
    "MAKE",
    "MODEL",
    "COMPNAME",
    "SUBJECT"
]].head(10)

,NHTSA ACTION NUMBER,CAMPNO,MAKE,MODEL,COMPNAME,SUBJECT
4,AQ09001,05E069000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
5,AQ09001,06E027000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
6,AQ09001,06E066000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
7,AQ09001,06E080000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
8,AQ09001,06E099000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
9,AQ09001,07E020000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
10,AQ09001,07E061000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
11,AQ09001,07E073000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
12,AQ09001,07E084000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS
13,AQ09001,08E044000,APEXCONE,APX9004,EXTERIOR LIGHTING,HID REPLACEMENT KIT RECALL CAMPAIGNS